[build]
  publish = "public"
  command = "hugo"
[context.production.environment]
  HUGO_VERSION = "0.67.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
[context.branch-deploy.environment]
  HUGO_VERSION = "0.67.0"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.67.0"

[[redirects]]
  from = "http://istmobiome.netlify.com/*"
  to = "https://istmobiome.rbind.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://istmobiome.netlify.com/*"
  to = "https://istmobiome.rbind.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://istmobiome.rbind.io/*"
  to = "https://istmobiome.rbind.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://https://istmobiome.github.io/"
  to = "https://istmobiome.rbind.io/:splat"
  status = 301
  force = true
