---
title: Test
linktitle: Test
summary:
date: 2019-12-13T15:58:49-05:00
lastmod: 2019-12-13T15:58:49-05:00
draft: false  # Is this a draft? true/false
toc: true  # Show table of contents? true/false
type: docs  # Do not modify.
weight: 5
raw: "https://raw.githubusercontent.com/rbind/blogdown-demo/master/content/post/2017-09-07-adding-htmlwidgets-to-r-markdown-posts.Rmd"

# Add menu entry to sidebar.
# - Substitute `example` with the name of your course/documentation folder.
# - name: Declare this menu item as a parent with ID `name`.
# - parent: Reference a parent ID if this page is a child.
# - weight: Position of link in menu.
bibliography: [cite.bib]
url_pdf: http://arxiv.org/pdf/1512.04133v1
url_cite: cite.bib
url_code: ""
url_slides: ""
url_video: ""
link-citations: true
menu:
  trans-water:
    parent: Environment Setup
    # parent: YourParentID
    weight: 5
---


This is an example of a table that does not render up except for the header.

```{r, message=FALSE, warning=FALSE}
library(DT)
library(tidyverse)
d1 <- iris %>%
  datatable()
d1
```

<hr/>

Until you use htmlwidgets and place it in an iframe like so...

```{r, message=FALSE, warning=FALSE}
library(htmlwidgets)
library(htmltools)

htmlwidgets::saveWidget(d1, file = "d1.html", selfcontained = TRUE)

```

<iframe seamless src="../d1/index.html" width="100%" height="500"></iframe>

here is the iframe code:
`<iframe seamless src="../d1/index.html" width="100%" height="500"></iframe>`

But the container is not responsive. However, the file "d1.html" is responsive.

<hr/>

This is an example of a table that does not show up at all.


```{r, message=FALSE, warning=FALSE}
dt <- DT::datatable(head(iris, 20))
```
